name: 'Get Latest Release'
description: 'Get the latest release from another repository and output that for use in other actions'
branding:
  icon: 'anchor'
  color: 'orange'
inputs:
  owner:
    description: 'The Github user or organization that owns the repository'
    required: false
  repo:
    description: 'The repository name'
    required: false
  repository:
    description: 'The repository name in full'
    required: false
  and_filters:
    description: 'A list of filters'
    required: false
  token:
    description: 'Github authentication token to use'
    required: false
  regex_filters:
    description: 'A list of filters where the values are regex'
    required: false
outputs:
  url: 
    description: The HTTP URL for this release
  assets_url:
    description: The REST API HTTP URL for this release's assets
  upload_url:
    description: The REST API HTTP URL for uploading to this release
  html_url:
    description: The REST API HTTP URL for this release
  id:
    description: ''
  node_id:
    description: The unique identifier for accessing this release in the GraphQL API
  tag_name:
    description: The name of the release's Git tag
  target_commitish:
    description: ''
  name:
    description: The title of the release.
  draft:
    description: Whether or not the release is a draft
  author_id:
    description: ''
  author_node_id:
    description: The unique identifier for accessing this release's author in the GraphQL API
  author_url:
    description: The REST API HTTP URL for this release's author
  author_login:
    description: The username used to login.
  author_html_url:
    description: The HTTP URL for this release's author
  author_type:
    description: ''
  author_site_admin:
    description: Whether or not this user is a site administrator.
  release_url:
    description: The url for the release page
runs:
  using: 'node12'
  main: 'main.js'
